/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultRouteImport } from './routes/result'
import { Route as TestRouteImport } from './routes/test'
import { Route as TypesRouteImport } from './routes/types'
import { Route as TypesIndexRouteImport } from './routes/types/index'
import { Route as TypesTypeRouteImport } from './routes/types/$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesIndexRoute = TypesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TypesRoute,
} as any)
const TypesTypeRoute = TypesTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => TypesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/test': typeof TestRoute
  '/types': typeof TypesRouteWithChildren
  '/types/$type': typeof TypesTypeRoute
  '/types/': typeof TypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/test': typeof TestRoute
  '/types/$type': typeof TypesTypeRoute
  '/types': typeof TypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/test': typeof TestRoute
  '/types': typeof TypesRouteWithChildren
  '/types/$type': typeof TypesTypeRoute
  '/types/': typeof TypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/result' | '/test' | '/types' | '/types/$type' | '/types/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/result' | '/test' | '/types/$type' | '/types'
  id:
    | '__root__'
    | '/'
    | '/result'
    | '/test'
    | '/types'
    | '/types/$type'
    | '/types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultRoute: typeof ResultRoute
  TestRoute: typeof TestRoute
  TypesRoute: typeof TypesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/': {
      id: '/types/'
      path: '/'
      fullPath: '/types/'
      preLoaderRoute: typeof TypesIndexRouteImport
      parentRoute: typeof TypesRoute
    }
    '/types/$type': {
      id: '/types/$type'
      path: '/$type'
      fullPath: '/types/$type'
      preLoaderRoute: typeof TypesTypeRouteImport
      parentRoute: typeof TypesRoute
    }
  }
}

interface TypesRouteChildren {
  TypesTypeRoute: typeof TypesTypeRoute
  TypesIndexRoute: typeof TypesIndexRoute
}

const TypesRouteChildren: TypesRouteChildren = {
  TypesTypeRoute: TypesTypeRoute,
  TypesIndexRoute: TypesIndexRoute,
}

const TypesRouteWithChildren = TypesRoute._addFileChildren(TypesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultRoute: ResultRoute,
  TestRoute: TestRoute,
  TypesRoute: TypesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
