// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaffkfahnjlgigmiucvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZmZrZmFobmpsZ2lnbWl1Y3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1NTMwOTUsImV4cCI6MjEwNjEyOTA5NX0.cCQ00hkWVOxLWc7MRYIiLyIuG9kuUurWr14xoMWRmg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});